version: "3"
services:
      postgres:
        image: postgres
        ports:
          - "5432:5432"
        environment:
          - "POSTGRES_PASSWORD=docker"
      dragons-lending-api:
        build: .
        depends_on:
          - postgres
        ports:
          - 8080:8080
        environment:
          - "SPRING_PROFILES_ACTIVE=dev"
          - "SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/"
